//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yatests.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int IdAnswer { get; set; }
        public int NumberAnswer { get; set; }
        public int IdQuestion { get; set; }
        public string ContentAnswer { get; set; }
        public int IdIsTrueOrFalse { get; set; }
    
        public virtual IsTrueOrFalse IsTrueOrFalse { get; set; }
        public virtual Question Question { get; set; }
    }
}
